add authentication and exercises modules
SpasErmenov/Fitness-app pull request #1
Opened 2024-01-15 12:14 UTC by SpasErmenov

2024-01-15 14:24 UTC, n-rodzhev requested changes

2024-01-15 14:24 UTC, n-rodzhev commented on .eslintrc.cjs
> +module.exports = {
```suggestion
{
  "parser": "@typescript-eslint/parser",
  "env": {
    "browser": true,
    "node": true
  },
  "plugins": ["@typescript-eslint", "import", "prettier", "jsx-a11y", "react", "react-hooks"],
  "extends": [
    "airbnb",
    "airbnb/hooks",
    "airbnb-typescript",
    "prettier",
    "plugin:prettier/recommended"
  ],
  "rules": {
    "jsx-a11y/mouse-events-have-key-events": "off",
    "import/prefer-default-export": "off",
    "no-plusplus": "off",
    "react/button-has-type": "off",
    "react/function-component-definition": "off",
    "react/hook-use-state": "warn",
    "react/jsx-handler-names": [
      "warn",
      {
        "checkLocalVariables": true
      }
    ],
    "react/jsx-no-useless-fragment": "warn",
    "react/jsx-props-no-spreading": "off",
    "react/require-default-props": "off",
    "react/destructuring-assignment": "off",
    "class-methods-use-this": "off",
    "react/react-in-jsx-scope": "off",
    "react/sort-prop-types": [
      "warn",
      {
        "callbacksLast": true
      }
    ],
  },
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"]
     }
        ]
      }
    }
  ]
}

```

2024-01-15 14:24 UTC, n-rodzhev commented on .eslintrc.cjs
> +  ignorePatterns: ['dist', '.eslintrc.cjs'],
create a `.eslintignore` file and add `vite.config.ts` there

2024-01-15 14:24 UTC, n-rodzhev commented on constants.ts
> +export const SERVER_URL_EXERCISES_FETCH_ALL = `${import.meta.env.VITE_SERVER_URL}/exercises/all`
these constants should be moved to a separate file `src/constants/api-endpoints.constants.ts`

2024-01-15 14:24 UTC, n-rodzhev commented on constants.ts
> +export const MAX_USERNAME_LENGTH = 10;
these constants should be moved to a separate file `src/validation/validation.constants.ts`

2024-01-15 14:24 UTC, n-rodzhev commented on package.json
you need to add pre-commit hooks

2024-01-15 14:24 UTC, n-rodzhev commented on package.json
also you will need to install additional packages for the eslint config

2024-01-15 14:24 UTC, n-rodzhev commented on .eslintrc.cjs
this file shouldn't be in Common JS

2024-01-15 14:24 UTC, n-rodzhev commented on src/App.css
delete this empty file

2024-01-15 14:24 UTC, n-rodzhev commented on src/App.tsx
> +import "./App.css";
delete this line

2024-01-15 14:24 UTC, n-rodzhev commented on public/vite.svg
change the favicon

2024-01-15 14:24 UTC, n-rodzhev commented on src/App.tsx
> +function App() {
use arrow function instead

2024-01-15 14:24 UTC, n-rodzhev commented on src/App.tsx
> +    <>
follow es-lint rule: `"react/jsx-no-useless-fragment"`

2024-01-15 14:24 UTC, n-rodzhev commented on src/App.tsx
> +export default App;
use named exports instead of default exports

2024-01-15 14:24 UTC, n-rodzhev commented on src/Enums/Enums.ts
rename the folder and file to lower case

2024-01-15 14:24 UTC, n-rodzhev commented on src/Interfaces/Interfaces.ts
rename the folder and file to lower case

2024-01-15 14:24 UTC, n-rodzhev commented on src/Interfaces/Interfaces.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
avoid disabling es-lint rules, or add a comment explaining why you need to disable this rule

2024-01-15 14:24 UTC, n-rodzhev commented on src/Interfaces/Interfaces.ts
> +        token: null | string;
fix formatting

2024-01-15 14:24 UTC, n-rodzhev commented on src/Interfaces/Interfaces.ts
> +message: string;
fix formatting

2024-01-15 14:24 UTC, n-rodzhev commented on src/assets/UsersFeedbackBlockPictures/user1.jpg
at this point you are using uppercase for component files and lowercase for others, either continue with the approach, or stick to one naming convention for all cases

2024-01-15 14:24 UTC, n-rodzhev commented on src/assets/UsersFeedbackBlockPictures/usersFeedbackBlockPictures.ts
> +interface IUsers {
move this interface

2024-01-15 14:24 UTC, n-rodzhev commented on src/assets/UsersFeedbackBlockPictures/usersFeedbackBlockPictures.ts
move this file to `src/constants/users-feedback-block-pictures.ts`

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.module.css
> +.dialogHeader {
use uppercase for classnames

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +import style from "./AuthDialog.module.css";
style import should always be last, if you want you can even add import-sort-plugin

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +import { AuthMode } from "../../Enums/Enums";
configure import aliasses to prevent such cases

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +  authMode: AuthMode | null;
add `declare type Maybe<T> = null | T` to the `src/global.d.ts` and use `Maybe` everywhere instead of `type | null`
```suggestion
  authMode: Maybe<AuthMode>;
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +    switch (authMode) {
you don't need `switch` here, use `if else` instead

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +    <Dialog open={open} onClose={onClose}>
```suggestion
    <Dialog open={open} onClose={props.onClose}>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +  const handleClickForSubmit = useCallback(async (username: string, password: string) => {
```suggestion
  const handleSubmit = useCallback(async (username: string, password: string) => {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +        <Button variant="text" size="small" onClick={handleClick}>
```suggestion
        <Button variant="text" size="small" onClick={props.onAuthModeChange}>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +            onSubmit={(username, password) =>
```suggestion
            onSubmit={handleSumbit}
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +              onSubmit={(username, password) =>
```suggestion
              onSubmit={handleSubmit}
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +  const handleClick = useCallback(() => {
delete this function

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.tsx
> +  const { authMode, open, onAuthModeChange, onClose, onFormSubmit } = props;
```suggestion
  const { authMode, open, onFormSubmit } = props;
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AvatarMenu/AvatarMenu.tsx
> +  const handleOpenUserMenu = (event: React.MouseEvent<HTMLElement>) => {
```suggestion
  const handleOpenUserMenu = (event: MouseEvent<HTMLElement>) => {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AvatarMenu/AvatarMenu.tsx
> +  const settings = ["Profile", "Logout"];
don't define such constants inside the component, extract this to separate file

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AvatarMenu/AvatarMenu.tsx
> +  const handleCloseUserMenu = (setting: string) => {
create a union type or use enum for settings

```suggestion
  const handleCloseUserMenu = (setting: SettingType) => () => {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AvatarMenu/AvatarMenu.tsx
> +          <Avatar alt="Remy Sharp" src="/static/images/avatar/2.jpg" />
what is this source? I don't see such directory

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AvatarMenu/AvatarMenu.tsx
> +        open={Boolean(anchorElUser)}
```suggestion
        open={!!anchorElUser}
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/AvatarMenu/AvatarMenu.tsx
> +          <MenuItem key={setting} onClick={() => handleCloseUserMenu(setting)}>
```suggestion
          <MenuItem key={setting} onClick={handleCloseUserMenu(setting)}>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Forms/LoginForm/LoginForm.tsx
> +  const [username, setUsername] = useState<string>("");
if you set the default value to string and it will only be string you don't need to explicitly specify the type here
```suggestion
  const [username, setUsername] = useState("");
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Forms/LoginForm/LoginForm.tsx
> +    (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
```suggestion
    (e: ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Forms/RegisterForm/RegisterForm.tsx
> +    (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
```suggestion
    (e: ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Forms/formValidation.utils.ts
move to src/validation/validation.utils.ts

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Forms/formValidation.utils.ts
> +  }
add line breaks after code blocks everywhere

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Header/Header.tsx
> +      <AppBar position="absolute" sx={{ bgcolor: "#1f2629" }}>
extract this color to constants

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Header/Header.tsx
> +                <Button color="inherit" onClick={onRegisterClick}>
```suggestion
                <Button color="inherit" onClick={props.onRegisterClick}>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Header/Header.tsx
> +                <Button color="inherit" onClick={onLoginClick}>
```suggestion
                <Button color="inherit" onClick={props.onLoginClick}>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Header/Header.tsx
> +                <Button color="inherit" onClick={onExercisesClick}>Exercises</Button>
```suggestion
                <Button color="inherit" onClick={props.onExercisesClick}>Exercises</Button>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Header/Header.tsx
> +                <AvatarMenu onLogoutClick={onLogoutClick}/>
```suggestion
                <AvatarMenu onLogoutClick={props.onLogoutClick}/>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/Header/Header.tsx
> +  const { onLoginClick, onRegisterClick, onLogoutClick, onExercisesClick, session } = props;
```suggestion
  const { session } = props;
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/UI/FeedbackCard/FeedbackCard.tsx
> +const FeedbackCard: FC<IFeedbackCardProps> = ({ name, imgPath }) => {
```suggestion
const FeedbackCard: FC<IFeedbackCardProps> = (props: IFeedbackCardProps) => {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/UI/FeedbackCard/FeedbackCard.tsx
> +import { FC } from "react";
add line break after imports

2024-01-15 14:24 UTC, n-rodzhev commented on src/components/UI/FeedbackCard/FeedbackCard.tsx
> +  return (
add destructuring of props above this line

2024-01-15 14:24 UTC, n-rodzhev commented on src/containers/AuthContainer.tsx
> +              navigate("/home");
extract paths to separate file `src/routes/paths.constnats.ts`

2024-01-15 14:24 UTC, n-rodzhev commented on src/containers/AuthContainer.tsx
> +          result = await authStore.register(username, password);
why for login you have different logic?

2024-01-15 14:24 UTC, n-rodzhev commented on src/containers/ExercisesContainer.tsx
> +  useEffect(() => {
don't do this, you need to fetch the exercise inside of the store using `autorun`

2024-01-15 14:24 UTC, n-rodzhev commented on src/containers/HeaderContainer.tsx
> +  const { session } = authStore;
stores should be at the top of the component body

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/CreateWorkout/CreateWorkout.module.css
> +    background-color: #f2f2f2;
create a file with variables for colors, `src/styles/variables.css`

2024-01-15 14:24 UTC, n-rodzhev commented on src/index.css
move file to 'src/styles.index.css'

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/CreateWorkout/CreateWorkout.tsx
the form should be separate component, src/forms/CreateWorkoutForm/CreateWorkoutForm.tsx

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/CreateWorkout/CreateWorkout.tsx
> +    <div className={styles.createWorkout}>
you should return a container inside the route

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/ExercisesPage/Exercises.tsx
> +    exercises: object | null;
`object` is not a good type, describe the exercise with an interface and use IExercise[] instead

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/ExercisesPage/Exercises.tsx
> +interface IExercises {
```suggestion
interface IExercisesProps {
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/ExercisesPage/Exercises.tsx
> +    <h1>a</h1>
the code here is still in progress, please add TODO comments in places where the code is not finished

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/ExercisesPage/ExercisesPage.tsx
you have both Exercises.tsx and ExercisesPage.tsx, remove one of them, for the name it is better to be Exercises.tsx

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.module.css
> +.text {
add line break between styles declaration blocks

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.module.css
> +.text {
also `text` is not a good name

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.tsx
> +  const { onJoinNowClick } = props;
delete lines 8 to 12

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.tsx
> +        <label onClick={handleClick}>
```suggestion
        <label onClick={props.onJoinNowClick}>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/FeedbackBlock/FeedbackBlock.tsx
> +const FeedbackBlock = () => {
add line breaks in this file

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.module.css
> +@media (max-width: 550px) {
move breakpoints to `styles/variables.css`

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/Footer/Footer.module.css
> +  font-family: "Inter", sans-serif;
move font to variables

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/Footer/Footer.tsx
> +        <p>Copyright &copy; 2023 Spas Ermenov. All Rights Reserved</p>
```suggestion
        <p>Copyright &copy; 2024 Spas Ermenov. All Rights Reserved</p>
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ImageBlock/ImageBlock.module.css
> +    url(../../../assets/landingBackground.jpg);
```suggestion
    url(assets/landingBackground.jpg);
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/ImageBlock/ImageBlock.tsx
move component to components folder not inside routes

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Landing/RateBlock/RateBlock.tsx
move component to components folder not inside routes

2024-01-15 14:24 UTC, n-rodzhev commented on src/routes/Router.tsx
> +function Router() {
use arrow function instead

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/AuthStore/AuthStore.ts
> +      setSessionToken: action
```suggestion
     setSession: action
```

2024-01-15 14:24 UTC, n-rodzhev commented on constants.ts
> +export const SERVER_URL = import.meta.env.VITE_SERVER_URL;
this constants should be moved to a separate file src/constants/environment.constants.ts
```suggestion
export const API_URL = import.meta.env.VITE_API_URL;
```

2024-01-15 14:24 UTC, n-rodzhev commented on constants.ts
> +export const SERVER_URL_EXERCISES_FETCH_ALL = `${import.meta.env.VITE_SERVER_URL}/exercises/all`
and you don't need `SERVER_URL` prefix for all endpoints

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/AuthStore/AuthStore.ts
> +      const data = {
`payload` will be better

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/AuthStore/AuthStore.ts
> +      if (error instanceof Error && error.message.includes("401")) {
you should send the status separately, not checking the content of the message

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/AuthStore/rest.service.ts
> +    data?: object
```suggestion
    body?: V
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/AuthStore/rest.service.ts
> +  static async request<T>(
```suggestion
  static async request<T, V = undefined>(
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/AuthStore/stores.ts
move this file to src/stores/stores.ts

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/ExercisesStore/ExercisesStore.ts
> +  public exercise: IExercise[] | null;
```suggestion
  public exercise: IExercise[];
```

2024-01-15 14:24 UTC, n-rodzhev commented on src/stores/ExercisesStore/ExercisesStore.ts
> +    this.exercise = null;
```suggestion
    this.exercise = [];
```

2024-01-15 14:24 UTC, n-rodzhev commented on tsconfig.node.json
delete this file

2024-01-15 14:24 UTC, n-rodzhev commented on vite.config.ts
> +import { defineConfig } from 'vite'
```suggestion
import react from '@vitejs/plugin-react';
import { defineConfig, loadEnv, UserConfig } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills';

// https://vitejs.dev/config/
export default ({ mode }: UserConfig) => {
  process.env = { ...process.env, ...loadEnv(mode || '', process.cwd()) };

  return defineConfig({
    plugins: [react(), nodePolyfills()],
    server: {
      host: true,
      port: Number(process.env.VITE_PORT) || 3000,
    },
    base: './',
    resolve: {
      alias: {
        '@': '/src',
      },
    },
  });
};

```

2024-01-15 14:34 UTC, SpasErmenov commented on .eslintrc.cjs
> +module.exports = {
Fixed

2024-01-15 21:47 UTC, SpasErmenov commented on .eslintrc.cjs
> +  ignorePatterns: ['dist', '.eslintrc.cjs'],
Fixed

2024-01-15 22:29 UTC, SpasErmenov commented on constants.ts
> +export const SERVER_URL_EXERCISES_FETCH_ALL = `${import.meta.env.VITE_SERVER_URL}/exercises/all`
Fixed

2024-01-15 22:33 UTC, SpasErmenov commented on constants.ts
> +export const MAX_USERNAME_LENGTH = 10;
Fixed

2024-01-15 22:35 UTC, SpasErmenov commented on src/App.css
Fixed

2024-01-15 22:36 UTC, SpasErmenov commented on src/App.tsx
> +import "./App.css";
Fixed

2024-01-15 22:52 UTC, SpasErmenov commented on public/vite.svg
I think you mean the Icon in the tab, if I'm not misstaken. I cahnge it to be dumbell.
Fixed

2024-01-15 22:54 UTC, SpasErmenov commented on src/App.tsx
> +function App() {
Fixed

2024-01-15 23:03 UTC, SpasErmenov commented on src/App.tsx
> +    <>
Fixed

2024-01-15 23:11 UTC, SpasErmenov commented on src/App.tsx
> +export default App;
Fixed

2024-01-15 23:16 UTC, SpasErmenov commented on src/Enums/Enums.ts
Fixed

2024-01-15 23:18 UTC, SpasErmenov commented on src/Interfaces/Interfaces.ts
Fixed

2024-01-15 23:24 UTC, SpasErmenov commented on src/Interfaces/Interfaces.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
Fix

2024-01-15 23:25 UTC, SpasErmenov commented on src/Interfaces/Interfaces.ts
> +        token: null | string;
Fix

2024-01-15 23:25 UTC, SpasErmenov commented on src/Interfaces/Interfaces.ts
> +message: string;
Fixed

2024-01-15 23:27 UTC, SpasErmenov commented on src/assets/UsersFeedbackBlockPictures/user1.jpg
Fixed

2024-01-15 23:29 UTC, SpasErmenov commented on src/assets/UsersFeedbackBlockPictures/usersFeedbackBlockPictures.ts
> +interface IUsers {
Fixed

2024-01-15 23:36 UTC, SpasErmenov commented on src/assets/UsersFeedbackBlockPictures/usersFeedbackBlockPictures.ts
Fixed

2024-01-15 23:48 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.module.css
> +.dialogHeader {
Fixed

2024-01-15 23:51 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +import style from "./AuthDialog.module.css";
Fixed

2024-01-16 11:51 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +  authMode: AuthMode | null;
Fixed

2024-01-16 15:09 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +    switch (authMode) {
Fixed

2024-01-16 15:13 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +    <Dialog open={open} onClose={onClose}>
Fixed

2024-01-16 15:17 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +  const handleClickForSubmit = useCallback(async (username: string, password: string) => {
Fixed

2024-01-16 15:18 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +        <Button variant="text" size="small" onClick={handleClick}>
Fixed

2024-01-16 15:18 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +            onSubmit={(username, password) =>
Fixed

2024-01-16 15:18 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +              onSubmit={(username, password) =>
Fixed

2024-01-16 15:18 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +  const handleClick = useCallback(() => {
Fixed

2024-01-16 15:25 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +  const { authMode, open, onAuthModeChange, onClose, onFormSubmit } = props;
Fixed

2024-01-16 15:27 UTC, SpasErmenov commented on src/components/AvatarMenu/AvatarMenu.tsx
> +  const handleOpenUserMenu = (event: React.MouseEvent<HTMLElement>) => {
Fixed

2024-01-16 15:29 UTC, SpasErmenov commented on src/components/AvatarMenu/AvatarMenu.tsx
> +  const settings = ["Profile", "Logout"];
Fixed

2024-01-16 15:34 UTC, SpasErmenov commented on src/components/AvatarMenu/AvatarMenu.tsx
> +  const handleCloseUserMenu = (setting: string) => {
Fixed

2024-01-16 15:41 UTC, SpasErmenov commented on src/components/AvatarMenu/AvatarMenu.tsx
> +          <Avatar alt="Remy Sharp" src="/static/images/avatar/2.jpg" />
Fixed

2024-01-16 15:42 UTC, SpasErmenov commented on src/components/AvatarMenu/AvatarMenu.tsx
> +        open={Boolean(anchorElUser)}
Fixed

2024-01-16 15:55 UTC, SpasErmenov commented on src/components/Forms/LoginForm/LoginForm.tsx
> +  const [username, setUsername] = useState<string>("");
Fixed

2024-01-16 15:56 UTC, SpasErmenov commented on src/components/Forms/LoginForm/LoginForm.tsx
> +    (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
Fixed

2024-01-16 15:59 UTC, SpasErmenov commented on src/components/Forms/RegisterForm/RegisterForm.tsx
> +    (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
Fixed

2024-01-16 16:11 UTC, SpasErmenov commented on src/components/Forms/formValidation.utils.ts
Fixed

2024-01-16 16:13 UTC, SpasErmenov commented on src/components/Forms/formValidation.utils.ts
> +  }
Fixed

2024-01-16 16:16 UTC, SpasErmenov commented on src/components/Header/Header.tsx
> +      <AppBar position="absolute" sx={{ bgcolor: "#1f2629" }}>
Fixed

2024-01-16 16:19 UTC, SpasErmenov commented on src/components/Header/Header.tsx
> +                <Button color="inherit" onClick={onRegisterClick}>
Fixed

2024-01-16 16:19 UTC, SpasErmenov commented on src/components/Header/Header.tsx
> +                <Button color="inherit" onClick={onLoginClick}>
Fixed

2024-01-16 16:19 UTC, SpasErmenov commented on src/components/Header/Header.tsx
> +                <Button color="inherit" onClick={onExercisesClick}>Exercises</Button>
Fixed

2024-01-16 16:19 UTC, SpasErmenov commented on src/components/Header/Header.tsx
> +                <AvatarMenu onLogoutClick={onLogoutClick}/>
Fixed

2024-01-16 16:19 UTC, SpasErmenov commented on src/components/Header/Header.tsx
> +  const { onLoginClick, onRegisterClick, onLogoutClick, onExercisesClick, session } = props;
Fixed

2024-01-16 19:46 UTC, SpasErmenov commented on src/components/UI/FeedbackCard/FeedbackCard.tsx
> +const FeedbackCard: FC<IFeedbackCardProps> = ({ name, imgPath }) => {
Fixed

2024-01-16 19:47 UTC, SpasErmenov commented on src/components/UI/FeedbackCard/FeedbackCard.tsx
> +import { FC } from "react";
Fixed

2024-01-16 19:47 UTC, SpasErmenov commented on src/components/UI/FeedbackCard/FeedbackCard.tsx
> +  return (
Fixed

2024-01-16 19:50 UTC, SpasErmenov commented on src/containers/AuthContainer.tsx
> +              navigate("/home");
Fixed

2024-01-16 19:54 UTC, SpasErmenov commented on src/containers/AuthContainer.tsx
> +          result = await authStore.register(username, password);
Let's discuss it, when you can.

2024-01-16 19:56 UTC, SpasErmenov commented on src/containers/HeaderContainer.tsx
> +  const { session } = authStore;
Fixed

2024-01-16 20:00 UTC, SpasErmenov commented on src/index.css
Fixed

2024-01-16 20:03 UTC, SpasErmenov commented on src/stores/AuthStore/stores.ts
Fixed

2024-01-16 20:04 UTC, SpasErmenov commented on tsconfig.node.json
Fixed

2024-01-16 20:08 UTC, SpasErmenov commented on src/stores/ExercisesStore/ExercisesStore.ts
> +  public exercise: IExercise[] | null;
Fixed

2024-01-16 20:09 UTC, SpasErmenov commented on src/stores/ExercisesStore/ExercisesStore.ts
> +    this.exercise = null;
Fixed

2024-01-16 20:12 UTC, SpasErmenov commented on constants.ts
> +export const SERVER_URL = import.meta.env.VITE_SERVER_URL;
Fixed

2024-01-16 20:15 UTC, SpasErmenov commented on src/stores/AuthStore/AuthStore.ts
> +      setSessionToken: action
Fixed

2024-01-16 20:17 UTC, SpasErmenov commented on src/routes/Router.tsx
> +function Router() {
Fixed

2024-01-16 20:19 UTC, SpasErmenov commented on src/routes/Landing/ImageBlock/ImageBlock.module.css
> +    url(../../../assets/landingBackground.jpg);
When chage by the suggestion, image disappear.

2024-01-16 20:20 UTC, SpasErmenov commented on src/routes/Landing/Footer/Footer.tsx
> +        <p>Copyright &copy; 2023 Spas Ermenov. All Rights Reserved</p>
Fixed

2024-01-16 20:23 UTC, SpasErmenov commented on src/routes/Landing/FeedbackBlock/FeedbackBlock.tsx
> +const FeedbackBlock = () => {
Fixed

2024-01-16 20:26 UTC, SpasErmenov commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.tsx
> +        <label onClick={handleClick}>
Fixed

2024-01-16 20:26 UTC, SpasErmenov commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.tsx
> +  const { onJoinNowClick } = props;
Fixed

2024-01-16 20:28 UTC, SpasErmenov commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.module.css
> +.text {
Add linebreakers.

Not fixed yet, I should think about better naming and change css file to uppercase.

2024-01-16 20:30 UTC, SpasErmenov commented on src/routes/ExercisesPage/ExercisesPage.tsx
Let's discuss this logic too.

2024-01-16 20:31 UTC, SpasErmenov commented on src/routes/ExercisesPage/Exercises.tsx
> +    <h1>a</h1>
Fixed

2024-01-16 20:32 UTC, SpasErmenov commented on src/routes/ExercisesPage/Exercises.tsx
> +interface IExercises {
Fixed

2024-01-17 15:00 UTC, SpasErmenov commented on src/containers/ExercisesContainer.tsx
> +  useEffect(() => {
Fixed

2024-01-17 22:00 UTC, n-rodzhev commented on src/containers/AuthContainer.tsx
> +          result = await authStore.register(username, password);
@SpasErmenov leave a todo as we discussed

2024-01-18 10:01 UTC, SpasErmenov commented on src/containers/AuthContainer.tsx
> +          result = await authStore.register(username, password);
Fixed

2024-01-18 10:08 UTC, SpasErmenov commented on src/routes/CreateWorkout/CreateWorkout.module.css
> +    background-color: #f2f2f2;
Fixed

2024-01-18 10:12 UTC, SpasErmenov commented on src/routes/ExercisesPage/Exercises.tsx
> +    exercises: object | null;
Fixed

2024-01-18 10:15 UTC, SpasErmenov commented on src/routes/ExercisesPage/ExercisesPage.tsx
Fixed

2024-01-18 10:27 UTC, SpasErmenov commented on src/routes/Landing/ConclusionBlock/ConclusionBlock.module.css
> +.text {
Fixed

2024-01-18 12:36 UTC, SpasErmenov commented on src/routes/Landing/Footer/Footer.module.css
> +  font-family: "Inter", sans-serif;
Fixed

2024-01-18 12:58 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.tsx
> +import { AuthMode } from "../../Enums/Enums";
Fixed

2024-01-19 09:54 UTC, n-rodzhev requested changes

2024-01-19 09:54 UTC, n-rodzhev commented on src/Interfaces/Interfaces.ts
> +export interface IResponse<T = any> {
```suggestion
export interface IResponse<T = unknown> {
```

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/AuthDialog/AuthDialog.module.css
> +    padding-right: 16px;
based on the jsx I saw, I guess you don't actually need padding here, if you need space between elements better use margin

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/CreateWorkout/CreateWorkout.module.css
> +.formFields {
this class is not used inside of component, remove this styles from here

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/FeedbackBlock/FeedbackBlock.module.css
> +  padding-bottom: 100px;
all these paddings are not needed, use the styles from `src/components/ConclusionBlock/ConclusionBlock.module.css` as example

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/FeedbackBlock/FeedbackBlock.module.css
> +  color: #1f2629;
move color to variables

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/FeedbackBlock/FeedbackBlock.module.css
> +  font-size: 20px;
move font to variables

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/Footer/Footer.module.css
> +  background-color: #1f2629;
move all colors from this file to variables

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/Footer/Footer.module.css
> +  padding-bottom: 50px;
all these paddings are not needed, use the styles from `src/components/ConclusionBlock/ConclusionBlock.module.css` as example

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/Home/Home.module.css
> +  background-color: #f2f2f2;
move color to variables

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/Home/Home.tsx
> +    navigate("/home/create-workout");
use path variable instead

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/ImageBlock/ImageBlock.module.css
> +  padding-bottom: 200px;
all these paddings are not needed, use the styles from `src/components/ConclusionBlock/ConclusionBlock.module.css` as example

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/ImageBlock/ImageBlock.module.css
> +  font-size: 50px;
move font-size to variables

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/RateBlock/RateBlock.module.css
> +  padding-bottom: 70px;
all these paddings are not needed, use the styles from `src/components/ConclusionBlock/ConclusionBlock.module.css` as example

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/RateBlock/RateBlock.module.css
> +  background-color: rgba(252, 203, 38, 0.85);
move color to variables

2024-01-19 09:54 UTC, n-rodzhev commented on src/components/RateBlock/RateBlock.module.css
> +  font-size: 3em;
stick to one unit, if you use pixels use it everywhere

2024-01-19 09:54 UTC, n-rodzhev commented on src/styles/index.css
> +  background-color: #1f2629;
move color to variables

2024-01-19 11:11 UTC, SpasErmenov commented on src/Interfaces/Interfaces.ts
> +export interface IResponse<T = any> {
Fixed

2024-01-19 11:17 UTC, SpasErmenov commented on src/components/AuthDialog/AuthDialog.module.css
> +    padding-right: 16px;
Fixed

2024-01-19 11:18 UTC, SpasErmenov commented on src/components/CreateWorkout/CreateWorkout.module.css
> +.formFields {
Fixed

2024-01-20 11:54 UTC, SpasErmenov commented on src/components/FeedbackBlock/FeedbackBlock.module.css
> +  color: #1f2629;
Fixed

2024-01-20 12:09 UTC, SpasErmenov commented on src/components/ImageBlock/ImageBlock.module.css
> +  font-size: 50px;
Fixed

2024-01-20 12:09 UTC, SpasErmenov commented on src/components/FeedbackBlock/FeedbackBlock.module.css
> +  padding-bottom: 100px;
Fixed

2024-01-20 12:10 UTC, SpasErmenov commented on src/components/FeedbackBlock/FeedbackBlock.module.css
> +  font-size: 20px;
Fixed

2024-01-20 12:38 UTC, SpasErmenov commented on src/components/Footer/Footer.module.css
> +  background-color: #1f2629;
Fixed

2024-01-20 12:38 UTC, SpasErmenov commented on src/components/Footer/Footer.module.css
> +  padding-bottom: 50px;
Fixed

2024-01-20 12:43 UTC, SpasErmenov commented on src/components/Home/Home.tsx
> +    navigate("/home/create-workout");
Fix

2024-01-20 12:44 UTC, SpasErmenov commented on src/components/Home/Home.module.css
> +  background-color: #f2f2f2;
Fixed

2024-01-20 12:44 UTC, SpasErmenov commented on src/components/ImageBlock/ImageBlock.module.css
> +  padding-bottom: 200px;
Fixed

2024-01-20 12:45 UTC, SpasErmenov commented on src/styles/index.css
> +  background-color: #1f2629;
Fixed

2024-01-20 13:07 UTC, SpasErmenov commented on src/components/RateBlock/RateBlock.module.css
> +  padding-bottom: 70px;
Fixed

2024-01-20 13:08 UTC, SpasErmenov commented on src/components/RateBlock/RateBlock.module.css
> +  background-color: rgba(252, 203, 38, 0.85);
Fixed

2024-01-20 13:08 UTC, SpasErmenov commented on src/components/RateBlock/RateBlock.module.css
> +  font-size: 3em;
Fixed

2024-01-20 13:21 UTC, n-rodzhev approved these changes

2024-01-20 13:27 UTC, merged